version: 2

models:
  - name: staging_raw_sales_data
    description: "Staging table for raw sales data from S3, parsed from a CSV file with semi-structured JSON fields."
    columns:
      - name: SaleID
        description: "Unique identifier for each sale transaction."
      - name: ProductID
        description: "Foreign key for the product in the sale."
      - name: CustomerID
        description: "Foreign key for the customer in the sale."
      - name: Quantity
        description: "Quantity of the product sold."
      - name: Date
        description: "Timestamp of the sale transaction."
      - name: LocationID
        description: "Foreign key for the location where the sale occurred."
      - name: PaymentID
        description: "Foreign key for the payment method used."
      - name: ShippingID
        description: "Foreign key for the shipping method used."
      - name: PromotionID
        description: "Foreign key for the promotion applied."
      - name: ReviewID
        description: "Foreign key for the customer review of the product."

      # Nested JSON Columns for Product
      - name: Product_ProductID
        description: "Unique identifier for the product (from the nested Product JSON field)."
      - name: Product_ProductName
        description: "Name of the product."
      - name: Product_Category
        description: "Category to which the product belongs."
      - name: Product_UnitCost
        description: "Cost price of the product."
      - name: Product_UnitPrice
        description: "Selling price of the product."

      # Nested JSON Columns for Customer
      - name: Customer_CustomerID
        description: "Unique identifier for the customer (from the nested Customer JSON field)."
      - name: Customer_CustomerName
        description: "Full name of the customer."
      - name: Customer_Email
        description: "Customer's email address."
      - name: Customer_PhoneNumber
        description: "Customer's phone number."
      - name: Customer_LoyaltyStatus
        description: "Customer's loyalty status (Bronze, Silver, or Gold)."

      # Nested JSON Columns for Location
      - name: Location_LocationID
        description: "Unique identifier for the location (from the nested Location JSON field)."
      - name: Location_Country
        description: "Country of the sale location."
      - name: Location_State
        description: "State or region of the sale location."
      - name: Location_City
        description: "City of the sale location."
      - name: Location_PostalCode
        description: "Postal code of the sale location."
      - name: Location_Region
        description: "Geographic region of the sale location."

      # Nested JSON Columns for Promotion
      - name: Promotion_PromotionID
        description: "Unique identifier for the promotion (from the nested Promotion JSON field)."
      - name: Promotion_PromotionName
        description: "Name of the promotion."
      - name: Promotion_DiscountRate
        description: "Discount rate applied by the promotion."

      # Nested JSON Columns for Shipping
      - name: Shipping_ShippingID
        description: "Unique identifier for the shipping method (from the nested Shipping JSON field)."
      - name: Shipping_Method
        description: "Shipping method (Standard, Express, etc.)."
      - name: Shipping_Cost
        description: "Cost of the shipping method used."

      # Nested JSON Columns for Review
      - name: Review_ReviewID
        description: "Unique identifier for the product review (from the nested Review JSON field)."
      - name: Review_ProductID
        description: "Product ID reviewed."
      - name: Review_CustomerID
        description: "Customer ID who reviewed the product."
      - name: Review_Rating
        description: "Customer's rating of the product."
      - name: Review_Comment
        description: "Customer's comment on the product."

      # Nested JSON Columns for Marketing Channel
      - name: MarketingChannel_ChannelID
        description: "Unique identifier for the marketing channel (from the nested MarketingChannel JSON field)."
      - name: MarketingChannel_ChannelName
        description: "Name of the marketing channel (Email, Social Media, etc.)."
