name: "dbt_transformations"
version: "1.0"
config-version: 2

profile: "emekamarkt"

model-paths: ["emekamarkt/models"]
analysis-paths: ["analyses"]   # Optional: if you're using analyses
test-paths: ["tests"]          # Optional: if you're using tests
seed-paths: ["seeds"]          # Optional: if you're using seed data
macro-paths: ["macros"]        # Optional: if you define macros
snapshot-paths: ["snapshots"]  # Optional: if you use snapshots

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"  # Use this instead of dbt_modules
